language: python
python:
  - "2.7"
# command to install dependencies
install:
  - sudo -H ./install_3stores.sh
  - "pip install -U -r requirements.txt"
  - "pip install -U -r requirements_dev.txt"
  - "pip install ."
  - "pip install -U pytest pytest-cov codecov"
# command to run tests
script: py.test --cov=knowledge_base -s -vv
after_success:
- codecov
