language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -U -r requirements.txt"
  - "pip install -e ."
  - "pip install -U pytest pytest-cov coveralls"
# command to run tests
script: py.test
